export enum ResponseErrorType {
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTORIZED = 'UNAUTORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  PRECONDITION_FAILED = 'PRECONDITION_FAILED',
  UNPROCESS_ENTITIY = 'UNPROCESS_ENTITIY',
  SERVER_ERROR = 'SERVER_ERROR',
}
